//Testimonials
$(document).ready(function(){
    $(".testimonials").owlCarousel({
      loop:true,
      margin:10,
      nav:true,
      dots: true,
      center:true,
      responsive:{
          0:{
              items:1
          },
          600:{
              items:1
          },
          1000:{
              items:1
          }
      }
    });
  });